users = [{
  'can_access_closed': True,
  'city': {'id': 1, 'title': 'Москва'},
  'common_count': 0,
  'first_name': 'Илья',
  'id': 2589920,
  'is_closed': False,
  'last_name': 'Ромашов',
  'track_code': '311960802rKIA6ncX93mGwj58Q5UZkXlVjV6k4f52PSqf16ir8-r349CqdFsjbFB-McBs4mnIpJSJGA',
  'weight': 0
},
 {'bdate': '3.2.1988',
  'books': '',
  'can_access_closed': True,
  'city': {'id': 1, 'title': 'Москва'},
  'common_count': 0,
  'first_name': 'Анатолий',
  'id': 1689465,
  'interests': '',
  'is_closed': False,
  'last_name': 'Коледин',
  'movies': '',
  'music': '',
  'track_code': '66b52f60AssA2lUxr2BnL-lbIYWEnD3UCCHSduh2X7OFYwZ3SyJzpgLJUjiYMmIvGmjVPVldWqMMMMg',
  'weight': 0
  },
 {'bdate': '20.4.1980',
  'can_access_closed': True,
  'city': {'id': 1, 'title': 'Москва'},
  'common_count': 0,
  'first_name': 'Вася',
  'id': 80342528,
  'is_closed': False,
  'last_name': 'Хайка',
  'track_code': '05a9270bleTtekruEhlKlwjrZ6rrGXjytANOk5t0wdRRxNCyvRTkibo_GbMqFhuc996QFQizE5apHEOE',
  'weight': 0
  },
 {'bdate': '24.1.1988',
  'books': '',
  'can_access_closed': True,
  'city': {'id': 1, 'title': 'Москва'},
  'common_count': 2,
  'first_name': 'Алексей',
  'id': 4438329,
  'interests': 'Фотография',
  'is_closed': False,
  'last_name': 'Комаров',
  'movies': '',
  'music': '',
  'track_code': 'fb24dfc46RUdf6R0Ljq7QsRLV_seJQsJpyT5G-cjLtCH8dLSMQiYeB4-oiVMbOxIMH-nT8PkbH6jNeM',
  'weight': 0
  }
]
